% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
\documentclass[
  10pt,
]{extarticle}
\usepackage{xcolor}
\usepackage[top=1.5in, bottom=1.5in, left=1.5in, right=1.5in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{xcolor}
\usepackage{hyperref}
\hypersetup{colorlinks=true, linkcolor=blue, urlcolor=blue, citecolor=blue}
\usepackage{float}
\usepackage{fvextra}
\usepackage{fancyhdr}
\usepackage{lastpage}
\usepackage{soul}
\usepackage{etoolbox}
\usepackage{microtype}
\usepackage{tcolorbox}
\usepackage{enumitem}
\usepackage{fancyvrb}
\usepackage{xspace}
\allowdisplaybreaks
\setcounter{tocdepth}{2}
\setcounter{secnumdepth}{0}
\floatplacement{figure}{H}
\makeatletter
\newcommand{\@subtitle}{}
\newcommand{\subtitle}[1]{\gdef\@subtitle{#1}}
\newcommand{\DocSubtitle}{\@subtitle}
\renewcommand{\maketitle}{
  \thispagestyle{plain}
  \null
  \vfill
  \begin{center}
    {\Large \textsc{\@title} \par}\vskip 0.5em
    {\LARGE \bfseries \@subtitle \par}\vskip 0.75em
    {\large \@author \par}\vskip 0.5em
    {\normalsize \@date \par}
  \end{center}
  \vfill
  \tableofcontents
  \vspace{1em}
  \clearpage
}
\AfterEndEnvironment{Highlighting}{\setcounter{CodeLine}{\numexpr\value{CodeLine}+\FV@CodeLineNo\relax}}
\makeatother
\fancypagestyle{plain}{
  \fancyhf{}
  \renewcommand{\headrulewidth}{0pt}
  \renewcommand{\footrulewidth}{0pt}
}
\pagestyle{fancy}
\fancyhf{}
\fancyfoot[C]{\small\textsc{Page}~\thepage~\textsc{of}~\pageref{LastPage}}
\fancyhead[L]{\textsc{Rento Saijo}}
\fancyhead[R]{\textsc{\DocSubtitle}}
\fancyhead[C]{\textsc{\rightmark}}
\renewcommand{\headrulewidth}{0.5pt}
\renewcommand{\footrulewidth}{0.5pt}
\newcounter{CodeLine}
\newcounter{cell}
\AtBeginEnvironment{Highlighting}{\stepcounter{cell}}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{
  frame=single,
  rulecolor=\color{black},
  framesep=2mm,
  label=\footnotesize Cell \thecell,
  labelposition=topline,
  commandchars=\\\{\},
  breaklines=true,
  breakanywhere=false,
  breaksymbol={},
  numbers=left,
  numbersep=3pt,
  firstnumber=\numexpr\value{CodeLine}+1\relax,
  fontsize=\small
}
\DefineVerbatimEnvironment{verbatim}{Verbatim}{
  breaklines=true,
  breakanywhere=true,
  numbers=left,
  numbersep=3pt,
  firstnumber=1,
  fontsize=\footnotesize
}
\newtcolorbox{problem}[1][]{
  title={\textsc{#1}}
}
\renewcommand{\contentsname}{Table of Contents}
\newcommand{\E}{\mathrm{E}}
\newcommand{\Var}{\mathrm{Var}}
\newcommand{\Cov}{\mathrm{Cov}}
\newcommand{\R}{\textsf{R}\xspace}
\newcommand{\SD}{\mathrm{SD}}
\newcommand{\SE}{\mathrm{SE}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={STA 209: Introduction to Time Series Analysis},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={blue},
  urlcolor={blue},
  pdfcreator={LaTeX via pandoc}}

\title{STA 209: Introduction to Time Series Analysis}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Homework 5}
\author{Rento Saijo}
\date{April 6, 2026}

\begin{document}
\maketitle

\section{Disclosure}\label{disclosure}

GPT-5.4 (High) on Codex was used to create the \texttt{YAML} portion and some \texttt{LaTeX} code to format the text/equations nicely. Page formatting code was also provided by Derin Gezgin. In the setup, chunk options were set for the document, and helper functions were defined for repetitive plotting and formatting code blocks.

\newpage

\section{Problem 1}\label{problem-1}

\begin{problem}[Problem 1]
Suppose a time series follows the following model:
\[
X_t = W_t - 0.2W_{t-2},
\]
where \(W_t \sim WN(0,\sigma_w^2)\), that is, \(\{W_t\}\) is a white noise with mean \(0\) and variance \(\sigma_w^2\).
\end{problem}

\newpage

\subsection{Problem 1 (a)}\label{problem-1-a}

\begin{problem}[Problem 1 (a)]
Determine its mean.
\end{problem}

Using the linearity of expectation and the fact that \(\mathrm{E}(W_t)=0\) for white noise,
\[
\begin{aligned}
\mathrm{E}(X_t)
&= \mathrm{E}(W_t - 0.2W_{t-2}) \\
&= \mathrm{E}(W_t) - 0.2\mathrm{E}(W_{t-2}) \\
&= 0 - 0.2(0) \\
&= 0.
\end{aligned}
\]

Hence,
\[
\mu_X(t) = \mu_X = 0,
\]
which is not a function of time \(t\).

\newpage

\subsection{Problem 1 (b)}\label{problem-1-b}

\begin{problem}[Problem 1 (b)]
Determine its Auto-Covariance Function (ACVF).
\end{problem}

For all integers \(h\),
\[
\gamma_X(t,h) = \mathrm{Cov}(X_{t+h},X_t) = \mathrm{E}[(X_{t+h}-\mu_{t+h})(X_t-\mu_t)].
\]
Since \(\mu_t = \mu_{t+h} = 0\),
\[
\begin{aligned}
\gamma_X(t,h)
&= \mathrm{E}(X_{t+h}X_t) \\
&= \mathrm{E}[(W_{t+h} - 0.2W_{t+h-2})(W_t - 0.2W_{t-2})] \\
&= \mathrm{E}(W_{t+h}W_t)
   - 0.2\mathrm{E}(W_{t+h}W_{t-2})
   - 0.2\mathrm{E}(W_{t+h-2}W_t)
   + 0.04\mathrm{E}(W_{t+h-2}W_{t-2}).
\end{aligned}
\]

Because \(\{W_t\}\) is white noise with mean \(0\),
\[
\mathrm{E}(W_aW_b) =
\begin{cases}
\sigma_w^2, & a=b,\\
0, & a \neq b.
\end{cases}
\]

Now, let us evaluate the expression case-by-case. If \(h=0\), then
\[
\begin{aligned}
\gamma_X(t,0)
&= \mathrm{E}(W_t^2)
   - 0.2\mathrm{E}(W_tW_{t-2})
   - 0.2\mathrm{E}(W_{t-2}W_t)
   + 0.04\mathrm{E}(W_{t-2}^2) \\
&= \sigma_w^2 - 0 - 0 + 0.04\sigma_w^2 \\
&= 1.04\sigma_w^2.
\end{aligned}
\]

If \(h=2\), then
\[
\begin{aligned}
\gamma_X(t,2)
&= \mathrm{E}(W_{t+2}W_t)
   - 0.2\mathrm{E}(W_{t+2}W_{t-2})
   - 0.2\mathrm{E}(W_tW_t)
   + 0.04\mathrm{E}(W_tW_{t-2}) \\
&= 0 - 0 - 0.2\sigma_w^2 + 0 \\
&= -0.2\sigma_w^2.
\end{aligned}
\]

If \(h=-2\), then
\[
\begin{aligned}
\gamma_X(t,-2)
&= \mathrm{E}(W_{t-2}W_t)
   - 0.2\mathrm{E}(W_{t-2}W_{t-2})
   - 0.2\mathrm{E}(W_{t-4}W_t)
   + 0.04\mathrm{E}(W_{t-4}W_{t-2}) \\
&= 0 - 0.2\sigma_w^2 - 0 + 0 \\
&= -0.2\sigma_w^2.
\end{aligned}
\]

If \(h \neq 0,\pm2\), then none of the time indices match, so every expectation is \(0\). Therefore,
\[
\gamma_X(t,h) = 0.
\]

Hence, the ACVF is
\[
\gamma_X(h) =
\begin{cases}
1.04\sigma_w^2, & h=0,\\
-0.2\sigma_w^2, & h=\pm2,\\
0, & h \in \mathbb{Z}\setminus\{0,-2,2\}.
\end{cases}
\]

This depends only on the lag \(h\), not on time \(t\).

\newpage

\subsection{Problem 1 (c)}\label{problem-1-c}

\begin{problem}[Problem 1 (c)]
Find and plot the Auto-Correlation Function (ACF).
\end{problem}

By definition,
\[
\rho_X(h) = \frac{\gamma_X(h)}{\gamma_X(0)}.
\]
Since \(\gamma_X(0)=1.04\sigma_w^2\),
\[
\rho_X(h) =
\begin{cases}
1, & h=0,\\
\dfrac{-0.2\sigma_w^2}{1.04\sigma_w^2} = -\dfrac{0.2}{1.04} = -\dfrac{5}{26} \approx -0.1923, & h=\pm2,\\
0, & h \in \mathbb{Z}\setminus\{0,-2,2\}.
\end{cases}
\]

So the ACF has one spike of height \(1\) at lag \(0\), two negative spikes of height \(-5/26 \approx -0.1923\) at lags \(-2\) and \(2\), and \(0\) at every other lag.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Numerical ACF values used for plotting.}
\NormalTok{p1\_lags }\OtherTok{\textless{}{-}} \SpecialCharTok{{-}}\DecValTok{10}\SpecialCharTok{:}\DecValTok{10}
\NormalTok{p1\_gamma\_over\_sigma2 }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}
\NormalTok{  p1\_lags }\SpecialCharTok{==} \DecValTok{0}\NormalTok{,}
  \FloatTok{1.04}\NormalTok{,}
  \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{abs}\NormalTok{(p1\_lags) }\SpecialCharTok{==} \DecValTok{2}\NormalTok{, }\SpecialCharTok{{-}}\FloatTok{0.2}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{)}
\NormalTok{p1\_rho }\OtherTok{\textless{}{-}}\NormalTok{ p1\_gamma\_over\_sigma2 }\SpecialCharTok{/} \FloatTok{1.04}

\CommentTok{\# Plot the ACF.}
\FunctionTok{acf\_stem\_plot}\NormalTok{(p1\_lags, p1\_rho, }\StringTok{\textquotesingle{}Problem 1: ACF\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-2-1} \end{center}

\newpage

\subsection{Problem 1 (d)}\label{problem-1-d}

\begin{problem}[Problem 1 (d)]
Is the process stationary? Justify.
\end{problem}

Yes, \(\{X_t\}\) is weakly stationary because of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The mean function is independent of time:
  \[
  \mu_X(t) = 0 = \mu_X.
  \]
\item
  The autocovariance function depends only on lag \(h\):
  \[
  \gamma_X(t,h) = \gamma_X(h) =
  \begin{cases}
  1.04\sigma_w^2, & h=0,\\
  -0.2\sigma_w^2, & h=\pm2,\\
  0, & h \in \mathbb{Z}\setminus\{0,-2,2\}.
  \end{cases}
  \]
\end{enumerate}

At lag \(h=0\), the ACVF is the variance, so
\[
\sigma_X^2(t) = \sigma_X^2 = \gamma_X(0) = 1.04\sigma_w^2,
\]
which is also constant over time. Therefore, the process satisfies both conditions for weak stationarity. Hence, \(\{X_t\}\) is stationary.

\newpage

\section{Problem 2}\label{problem-2}

\begin{problem}[Problem 2]
For the following MA process
\[
X_t = W_{t-1} + 2W_t + W_{t+1}
\]
\end{problem}

\newpage

\subsection{Problem 2 (a)}\label{problem-2-a}

\begin{problem}[Problem 2 (a)]
Determine its mean.
\end{problem}

Using the linearity of expectation and the fact that \(\mathrm{E}(W_t)=0\),
\[
\begin{aligned}
\mathrm{E}(X_t)
&= \mathrm{E}(W_{t-1} + 2W_t + W_{t+1}) \\
&= \mathrm{E}(W_{t-1}) + 2\mathrm{E}(W_t) + \mathrm{E}(W_{t+1}) \\
&= 0 + 2(0) + 0 \\
&= 0.
\end{aligned}
\]

Hence,
\[
\mu_X(t) = \mu_X = 0,
\]
which is not a function of time \(t\).

\newpage

\subsection{Problem 2 (b)}\label{problem-2-b}

\begin{problem}[Problem 2 (b)]
Determine its Auto-Covariance Function (ACVF).
\end{problem}

For all integers \(h\),
\[
\gamma_X(t,h) = \mathrm{Cov}(X_{t+h},X_t) = \mathrm{E}[(X_{t+h}-\mu_{t+h})(X_t-\mu_t)].
\]
Since \(\mu_t = \mu_{t+h} = 0\),
\[
\gamma_X(t,h) = \mathrm{E}(X_{t+h}X_t).
\]
Also,
\[
X_{t+h} = W_{t+h-1} + 2W_{t+h} + W_{t+h+1}.
\]
Therefore,
\[
\begin{aligned}
\gamma_X(t,h)
&= \mathrm{E}[(W_{t+h-1} + 2W_{t+h} + W_{t+h+1})(W_{t-1} + 2W_t + W_{t+1})] \\
&= \mathrm{E}(W_{t+h-1}W_{t-1})
 + 2\mathrm{E}(W_{t+h-1}W_t)
 + \mathrm{E}(W_{t+h-1}W_{t+1}) \\
&\quad + 2\mathrm{E}(W_{t+h}W_{t-1})
 + 4\mathrm{E}(W_{t+h}W_t)
 + 2\mathrm{E}(W_{t+h}W_{t+1}) \\
&\quad + \mathrm{E}(W_{t+h+1}W_{t-1})
 + 2\mathrm{E}(W_{t+h+1}W_t)
 + \mathrm{E}(W_{t+h+1}W_{t+1}).
\end{aligned}
\]

Again, since \(\{W_t\}\) is white noise,
\[
\mathrm{E}(W_aW_b) =
\begin{cases}
\sigma_w^2, & a=b,\\
0, & a \neq b.
\end{cases}
\]

Now evaluate case-by-case. If \(h=0\), then
\[
\begin{aligned}
\gamma_X(t,0)
&= \mathrm{E}(W_{t-1}^2)
 + 2\mathrm{E}(W_{t-1}W_t)
 + \mathrm{E}(W_{t-1}W_{t+1}) \\
&\quad + 2\mathrm{E}(W_tW_{t-1})
 + 4\mathrm{E}(W_t^2)
 + 2\mathrm{E}(W_tW_{t+1}) \\
&\quad + \mathrm{E}(W_{t+1}W_{t-1})
 + 2\mathrm{E}(W_{t+1}W_t)
 + \mathrm{E}(W_{t+1}^2) \\
&= \sigma_w^2 + 0 + 0 + 0 + 4\sigma_w^2 + 0 + 0 + 0 + \sigma_w^2 \\
&= 6\sigma_w^2.
\end{aligned}
\]

If \(h=1\), then
\[
\begin{aligned}
\gamma_X(t,1)
&= \mathrm{E}(W_tW_{t-1})
 + 2\mathrm{E}(W_tW_t)
 + \mathrm{E}(W_tW_{t+1}) \\
&\quad + 2\mathrm{E}(W_{t+1}W_{t-1})
 + 4\mathrm{E}(W_{t+1}W_t)
 + 2\mathrm{E}(W_{t+1}W_{t+1}) \\
&\quad + \mathrm{E}(W_{t+2}W_{t-1})
 + 2\mathrm{E}(W_{t+2}W_t)
 + \mathrm{E}(W_{t+2}W_{t+1}) \\
&= 0 + 2\sigma_w^2 + 0 + 0 + 0 + 2\sigma_w^2 + 0 + 0 + 0 \\
&= 4\sigma_w^2.
\end{aligned}
\]

If \(h=-1\), then
\[
\begin{aligned}
\gamma_X(t,-1)
&= \mathrm{E}(W_{t-2}W_{t-1})
 + 2\mathrm{E}(W_{t-2}W_t)
 + \mathrm{E}(W_{t-2}W_{t+1}) \\
&\quad + 2\mathrm{E}(W_{t-1}W_{t-1})
 + 4\mathrm{E}(W_{t-1}W_t)
 + 2\mathrm{E}(W_{t-1}W_{t+1}) \\
&\quad + \mathrm{E}(W_tW_{t-1})
 + 2\mathrm{E}(W_tW_t)
 + \mathrm{E}(W_tW_{t+1}) \\
&= 0 + 0 + 0 + 2\sigma_w^2 + 0 + 0 + 0 + 2\sigma_w^2 + 0 \\
&= 4\sigma_w^2.
\end{aligned}
\]

If \(h=2\), then
\[
\begin{aligned}
\gamma_X(t,2)
&= \mathrm{E}(W_{t+1}W_{t-1})
 + 2\mathrm{E}(W_{t+1}W_t)
 + \mathrm{E}(W_{t+1}W_{t+1}) \\
&\quad + 2\mathrm{E}(W_{t+2}W_{t-1})
 + 4\mathrm{E}(W_{t+2}W_t)
 + 2\mathrm{E}(W_{t+2}W_{t+1}) \\
&\quad + \mathrm{E}(W_{t+3}W_{t-1})
 + 2\mathrm{E}(W_{t+3}W_t)
 + \mathrm{E}(W_{t+3}W_{t+1}) \\
&= 0 + 0 + \sigma_w^2 + 0 + 0 + 0 + 0 + 0 + 0 \\
&= \sigma_w^2.
\end{aligned}
\]

If \(h=-2\), then
\[
\begin{aligned}
\gamma_X(t,-2)
&= \mathrm{E}(W_{t-3}W_{t-1})
 + 2\mathrm{E}(W_{t-3}W_t)
 + \mathrm{E}(W_{t-3}W_{t+1}) \\
&\quad + 2\mathrm{E}(W_{t-2}W_{t-1})
 + 4\mathrm{E}(W_{t-2}W_t)
 + 2\mathrm{E}(W_{t-2}W_{t+1}) \\
&\quad + \mathrm{E}(W_{t-1}W_{t-1})
 + 2\mathrm{E}(W_{t-1}W_t)
 + \mathrm{E}(W_{t-1}W_{t+1}) \\
&= 0 + 0 + 0 + 0 + 0 + 0 + \sigma_w^2 + 0 + 0 \\
&= \sigma_w^2.
\end{aligned}
\]

If \(|h|>2\), then no indices match, so every expectation is \(0\). Therefore,
\[
\gamma_X(t,h) = 0.
\]

Hence, the ACVF is
\[
\gamma_X(h) =
\begin{cases}
6\sigma_w^2, & h=0,\\
4\sigma_w^2, & h=\pm1,\\
\sigma_w^2, & h=\pm2,\\
0, & h \in \mathbb{Z}\setminus\{-2,-1,0,1,2\}.
\end{cases}
\]

This depends only on the lag \(h\), not on time \(t\).

\newpage

\subsection{Problem 2 (c)}\label{problem-2-c}

\begin{problem}[Problem 2 (c)]
Find and plot the Auto-Correlation Function (ACF).
\end{problem}

By definition,
\[
\rho_X(h) = \frac{\gamma_X(h)}{\gamma_X(0)}.
\]
Since \(\gamma_X(0)=6\sigma_w^2\),
\[
\rho_X(h) =
\begin{cases}
1, & h=0,\\
\dfrac{4\sigma_w^2}{6\sigma_w^2} = \dfrac{2}{3} \approx 0.6667, & h=\pm1,\\
\dfrac{\sigma_w^2}{6\sigma_w^2} = \dfrac{1}{6} \approx 0.1667, & h=\pm2,\\
0, & h \in \mathbb{Z}\setminus\{-2,-1,0,1,2\}.
\end{cases}
\]

So the ACF has a spike of height \(1\) at lag \(0\), positive spikes of height \(2/3 \approx 0.6667\) at lags \(-1\) and \(1\), smaller positive spikes of height \(1/6 \approx 0.1667\) at lags \(-2\) and \(2\), and \(0\) at every other lag.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Numerical ACF values used for plotting.}
\NormalTok{p2\_lags }\OtherTok{\textless{}{-}} \SpecialCharTok{{-}}\DecValTok{10}\SpecialCharTok{:}\DecValTok{10}
\NormalTok{p2\_gamma\_over\_sigma2 }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}
\NormalTok{  p2\_lags }\SpecialCharTok{==} \DecValTok{0}\NormalTok{,}
  \DecValTok{6}\NormalTok{,}
  \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{abs}\NormalTok{(p2\_lags) }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, }\DecValTok{4}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(}\FunctionTok{abs}\NormalTok{(p2\_lags) }\SpecialCharTok{==} \DecValTok{2}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{))}
\NormalTok{)}
\NormalTok{p2\_rho }\OtherTok{\textless{}{-}}\NormalTok{ p2\_gamma\_over\_sigma2 }\SpecialCharTok{/} \DecValTok{6}

\CommentTok{\# Plot the ACF.}
\FunctionTok{acf\_stem\_plot}\NormalTok{(p2\_lags, p2\_rho, }\StringTok{\textquotesingle{}Problem 2: ACF\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-3-1} \end{center}

\newpage

\subsection{Problem 2 (d)}\label{problem-2-d}

\begin{problem}[Problem 2 (d)]
Is the process stationary? Justify.
\end{problem}

Yes, \(\{X_t\}\) is weakly stationary because of the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The mean function is independent of time:
  \[
  \mu_X(t) = 0 = \mu_X.
  \]
\item
  The autocovariance function depends only on lag \(h\):
  \[
  \gamma_X(t,h) = \gamma_X(h) =
  \begin{cases}
  6\sigma_w^2, & h=0,\\
  4\sigma_w^2, & h=\pm1,\\
  \sigma_w^2, & h=\pm2,\\
  0, & h \in \mathbb{Z}\setminus\{-2,-1,0,1,2\}.
  \end{cases}
  \]
\end{enumerate}

At lag \(h=0\), the ACVF is the variance, so
\[
\sigma_X^2(t) = \sigma_X^2 = \gamma_X(0) = 6\sigma_w^2,
\]
which is constant over time. Therefore, the process satisfies both conditions for weak stationarity. Hence, \(\{X_t\}\) is stationary.

\newpage

\section{Problem 3}\label{problem-3}

\begin{problem}[Problem 3]
For your data analysis project, do the following:
\end{problem}

For Problem 3, I use the three game-by-game even-strength series
\[
G_t = \texttt{Goals Saved Above Expected}, \qquad S_t = \texttt{Save \%}, \qquad X_t = \texttt{Team xGF\%}.
\]
Here, \(G_t\) is measured in goals, \(S_t\) is a proportion, and \(X_t\) is measured in percentage points. The time index \(t\) is the matched career game number, so for both goalies \(t = 1,2,\ldots,285\). Blackwood's matched sample covers 2018-12-18 through 2026-03-28, with 152 games for New Jersey, 63 for San Jose, and 70 for Colorado. Shesterkin's matched sample covers 2020-01-07 through 2025-11-04, and all 285 games are with the Rangers. I went back-and-forth on this throughout the previous homeworks and the presentation, but I've settled that using game-by-game \(G_t\) as the response makes more sense here than using cumulative GSAx, because the cumulative series mechanically builds in low-frequency drift. The predictor choice also makes sense, I believe: \(X_t\) measures the team process environment, while \(S_t\) measures the goalie's game-level stopping outcome. However, for predictive use, only lagged predictor values are admissible. Therefore, in parts (d) and (e), I interpret only predictor leads and do not use same-game or future predictor information.

\newpage

\subsection{Problem 3 (a)}\label{problem-3-a}

\begin{problem}[Problem 3 (a)]
Report your time series plot for all study variables. Using these plots share if your time series is non-stationary and justify.
\end{problem}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Raw game{-}by{-}game Blackwood series.}
\FunctionTok{with\_family}\NormalTok{(\{}
  \FunctionTok{plot\_raw\_series}\NormalTok{(blackwood\_project, }\StringTok{\textquotesingle{}Blackwood\textquotesingle{}}\NormalTok{, }\AttributeTok{add\_trade\_lines =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-5-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Raw game{-}by{-}game Shesterkin series.}
\FunctionTok{with\_family}\NormalTok{(\{}
  \FunctionTok{plot\_raw\_series}\NormalTok{(shesterkin\_project, }\StringTok{\textquotesingle{}Shesterkin\textquotesingle{}}\NormalTok{, }\AttributeTok{add\_trade\_lines =} \ConstantTok{FALSE}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-6-1} \end{center}

\subsubsection{Blackwood}\label{blackwood}

\begin{itemize}
\tightlist
\item
  \(G_t\): This is Blackwood's game-by-game even-strength GSAx series, measured in goals, over 285 matched career games from 2018-12-18 through 2026-03-28. The plot does not show a sustained trend, either linear or nonlinear. Instead, it oscillates around a roughly stable center near \(-0.04\) goals, with isolated positive and negative spikes. There is no repeated seasonal pattern in the game index. Since this is sports performance, a stable seasonal cycle is not expected conceptually as opposed to something like temperature, for example. The variability looks fairly stable over time, so there is no strong visual evidence of heteroscedasticity (you may be able to deduce minor fanning out). The series is not especially volatile. The statistical range is -5.1899 to 2.9214, so the total range is 8.1113 goals.
\item
  \(S_t\): This is Blackwood's game-by-game even-strength save percentage series, measured as a proportion on \([0,1]\). The mean behavior appears approximately stable around \(0.9023\), with no clear linear or nonlinear trend through the matched game index. There is no visible seasonal pattern. The series has a few sharp downward games, but these appear as isolated dips rather than a repeating cycle. The spread appears reasonably constant over time, so the variance looks approximately homoscedastic rather than heteroscedastic (again, you may be able to deduce minor fanning out). There is no strong visual evidence of volatility clustering, although you be able to deduce a few outliers. The statistical range is 0.5 to 1, so the total range is 0.5.
\item
  \(X_t\): This is Blackwood's team game-by-game even-strength xGF\% series, measured in percentage points. The plot fluctuates around \(48.59\) percent and does not show a sustained deterministic trend (if you break it into pieces, you can see a linear upward trend towards the latter); the franchise changes may create local level differences, but the overall pattern is still irregular rather than trending. There is no visual seasonality. The ups and downs appear irregular from game to game and do not repeat in a fixed cycle. The variance looks approximately constant over time, so I do not see strong heteroscedasticity or volatility clustering in this series. The statistical range is 21.03 to 80.66, so the total range is 59.63 percentage points.
\item
  Overall conclusion: From the time-series plots, the Blackwood series do not look non-stationary. The means appear approximately time-invariant, and the spreads are fairly stable.
\end{itemize}

\subsubsection{Shesterkin}\label{shesterkin}

\begin{itemize}
\tightlist
\item
  \(G_t\): This is Shesterkin's game-by-game even-strength GSAx series, measured in goals, over 285 matched career games from 2020-01-07 through 2025-11-04. The plot fluctuates around a stable positive center near \(0.2329\) goals and does not show a visible linear or nonlinear trend. There is no visible seasonal cycle. The spikes are irregular rather than repeating. The spread appears fairly stable over time, so the variance looks approximately homoscedastic (again, you may be able to deduce minor fanning out). There is no sustained volatility clustering. The statistical range is -4.288 to 2.857, so the total range is 7.1451 goals.
\item
  \(S_t\): This is Shesterkin's game-by-game even-strength save percentage series, measured as a proportion. The series fluctuates around \(0.9163\), with occasional large downward games, but it does not show a systematic linear or nonlinear trend. There is no clear repeated seasonal pattern. The spread appears approximately constant over time, so the series looks homoscedastic rather than heteroscedastic (again, you may be able to deduce minor fanning out). There is no strong visual evidence of volatility clustering, although there are some obvious outliers. The statistical range is 0.4444 to 1, so the total range is 0.5556.
\item
  \(X_t\): This is Shesterkin's team game-by-game even-strength xGF\% series, measured in percentage points. The plot oscillates around \(49.07\) percent, and the movement appears irregular rather than trending. There is no visible seasonal pattern. The spread looks fairly stable over time, so there is no strong visual evidence of heteroscedasticity or volatility clustering. The statistical range is 21.68 to 79.42, so the total range is 57.74 percentage points.
\item
  Overall conclusion: From the plots, the Shesterkin series also appear stationary. The means look approximately stable, and the variances are fairly constant.
\end{itemize}

\newpage

\subsection{Problem 3 (b)}\label{problem-3-b}

\begin{problem}[Problem 3 (b)]
Use the ADF test to check if each of your time series is stationary or not.
\end{problem}

For each series, I use the Augmented Dickey-Fuller test with
\[
H_0: \text{the series is non-stationary}, \qquad
H_a: \text{the series is stationary},
\]
at significance level \(\alpha = 0.05\).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Run the ADF tests for the six raw game{-}by{-}game series.}
\NormalTok{tseries}\SpecialCharTok{::}\FunctionTok{adf.test}\NormalTok{(blackwood\_gbgs}\SpecialCharTok{$}\NormalTok{gsax\_ev)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  blackwood_gbgs$gsax_ev
## Dickey-Fuller = -6.7931, Lag order = 6, p-value = 0.01
## alternative hypothesis: stationary
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tseries}\SpecialCharTok{::}\FunctionTok{adf.test}\NormalTok{(blackwood\_gbgs}\SpecialCharTok{$}\NormalTok{sv\_pct\_ev)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  blackwood_gbgs$sv_pct_ev
## Dickey-Fuller = -6.0001, Lag order = 6, p-value = 0.01
## alternative hypothesis: stationary
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tseries}\SpecialCharTok{::}\FunctionTok{adf.test}\NormalTok{(blackwood\_gbgs}\SpecialCharTok{$}\NormalTok{team\_xg\_pct\_ev)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  blackwood_gbgs$team_xg_pct_ev
## Dickey-Fuller = -4.1809, Lag order = 6, p-value = 0.01
## alternative hypothesis: stationary
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tseries}\SpecialCharTok{::}\FunctionTok{adf.test}\NormalTok{(shesterkin\_gbgs}\SpecialCharTok{$}\NormalTok{gsax\_ev)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  shesterkin_gbgs$gsax_ev
## Dickey-Fuller = -6.7433, Lag order = 6, p-value = 0.01
## alternative hypothesis: stationary
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tseries}\SpecialCharTok{::}\FunctionTok{adf.test}\NormalTok{(shesterkin\_gbgs}\SpecialCharTok{$}\NormalTok{sv\_pct\_ev)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  shesterkin_gbgs$sv_pct_ev
## Dickey-Fuller = -6.9665, Lag order = 6, p-value = 0.01
## alternative hypothesis: stationary
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tseries}\SpecialCharTok{::}\FunctionTok{adf.test}\NormalTok{(shesterkin\_gbgs}\SpecialCharTok{$}\NormalTok{team\_xg\_pct\_ev)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  shesterkin_gbgs$team_xg_pct_ev
## Dickey-Fuller = -6.8293, Lag order = 6, p-value = 0.01
## alternative hypothesis: stationary
\end{verbatim}

\begin{center}
\scriptsize
\begin{table}[H]

\caption{\label{tab:adf-results-table}ADF Test Results}
\centering
\begin{tabular}[t]{cccccc}
\toprule
Goalie & Series & DF & Lag & P-value & Decision\\
\midrule
Blackwood & $G_t$ & -6.7931 & 6 & <0.01 & Reject $H_0$\\
Blackwood & $S_t$ & -6.0001 & 6 & <0.01 & Reject $H_0$\\
Blackwood & $X_t$ & -4.1809 & 6 & <0.01 & Reject $H_0$\\
Shesterkin & $G_t$ & -6.7433 & 6 & <0.01 & Reject $H_0$\\
Shesterkin & $S_t$ & -6.9665 & 6 & <0.01 & Reject $H_0$\\
\addlinespace
Shesterkin & $X_t$ & -6.8293 & 6 & <0.01 & Reject $H_0$\\
\bottomrule
\end{tabular}
\end{table}
\normalsize
\end{center}

Using the reported test statistics and p-values:

\begin{itemize}
\tightlist
\item
  Blackwood \(G_t\): DF statistic \(=-6.7931\), lag order \(=6\), p-value \textless0.01. Since \(p < 0.05\), reject \(H_0\). Therefore, \(G_t\) is stationary.
\item
  Blackwood \(S_t\): DF statistic \(=-6.0001\), lag order \(=6\), p-value \textless0.01. Since \(p < 0.05\), reject \(H_0\). Therefore, \(S_t\) is stationary.
\item
  Blackwood \(X_t\): DF statistic \(=-4.1809\), lag order \(=6\), p-value \textless0.01. Since \(p < 0.05\), reject \(H_0\). Therefore, \(X_t\) is stationary.
\item
  Shesterkin \(G_t\): DF statistic \(=-6.7433\), lag order \(=6\), p-value \textless0.01. Since \(p < 0.05\), reject \(H_0\). Therefore, \(G_t\) is stationary.
\item
  Shesterkin \(S_t\): DF statistic \(=-6.9665\), lag order \(=6\), p-value \textless0.01. Since \(p < 0.05\), reject \(H_0\). Therefore, \(S_t\) is stationary.
\item
  Shesterkin \(X_t\): DF statistic \(=-6.8293\), lag order \(=6\), p-value \textless0.01. Since \(p < 0.05\), reject \(H_0\). Therefore, \(X_t\) is stationary.
\end{itemize}

\newpage

\subsection{Problem 3 (c)}\label{problem-3-c}

\begin{problem}[Problem 3 (c)]
Is there a trend in your time series (for each variable)? Why? If yes, then model the trend present in all the variables and report the fitted trend models.
\end{problem}

From part (a), none of the six raw game-by-game series shows a clear deterministic trend, and from part (b), all six ADF tests reject non-stationarity. Therefore, I do not fit nonconstant deterministic trend models in this section. Instead, I treat each series as fluctuating around a constant mean:
\[
Y_t = \mu_Y + W_t.
\]

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Estimated constant means for the six game{-}by{-}game series.}
\FunctionTok{rbind}\NormalTok{(}
  \AttributeTok{Blackwood =} \FunctionTok{round}\NormalTok{(blackwood\_project}\SpecialCharTok{$}\NormalTok{means, }\DecValTok{6}\NormalTok{),}
  \AttributeTok{Shesterkin =} \FunctionTok{round}\NormalTok{(shesterkin\_project}\SpecialCharTok{$}\NormalTok{means, }\DecValTok{6}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              gsax_ev sv_pct_ev team_xg_pct_ev
## Blackwood  -0.039974  0.902272       48.59140
## Shesterkin  0.232914  0.916254       49.06553
\end{verbatim}

For Blackwood, the fitted mean models are
\[
\begin{aligned}
G_t &= -0.039974 + W_t,\\
S_t &= 0.902272 + W_t,\\
X_t &= 48.591400 + W_t.
\end{aligned}
\]

For Shesterkin, the fitted mean models are
\[
\begin{aligned}
G_t &= 0.232914 + W_t,\\
S_t &= 0.916254 + W_t,\\
X_t &= 49.065530 + W_t.
\end{aligned}
\]

So there is no nonconstant deterministic trend to remove. Also, there is no seasonal component to remove here. Since \(t\) is a game index rather than a monthly, quarterly, or weekly calendar time scale, there is no fixed seasonal frequency built into the series conceptually. This is also consistent with the original time-series plots in part (a), which do not show any repeated seasonal cycle. Therefore, in parts (d) and (e), the detrended and deseasonalized series are just the original series in their original units.

\newpage

\subsection{Problem 3 (d)}\label{problem-3-d}

\begin{problem}[Problem 3 (d)]
Using the detrended and deseasonalized variables, make CCF plot and scatterplots for your response and predictors (one at a time) and discuss the relationship.
\end{problem}

Since only past predictor values are usable for forecasting, I interpret only predictor leads in this section. In \(\texttt{ccf}(x,y)\), negative lags correspond to the predictor leading the response. So the CCF plots below display only those negative-lag correlations, rewritten as positive lead lengths in games.

\subsubsection{Blackwood}\label{blackwood-1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Lead{-}only CCF plots for Blackwood.}
\FunctionTok{with\_family}\NormalTok{(\{}
  \FunctionTok{plot\_goalie\_ccf}\NormalTok{(blackwood\_project, }\StringTok{\textquotesingle{}Blackwood\textquotesingle{}}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-9-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Scatterplots of lagged save percentage against future GSAx for Blackwood.}
\FunctionTok{with\_family}\NormalTok{(\{}
  \FunctionTok{plot\_lagged\_scatter\_grid}\NormalTok{(blackwood\_project, }\StringTok{\textquotesingle{}Blackwood\textquotesingle{}}\NormalTok{, }\AttributeTok{predictor =} \StringTok{\textquotesingle{}sv\textquotesingle{}}\NormalTok{, }\AttributeTok{leads =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{9}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-10-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Scatterplots of lagged team xGF\% against future GSAx for Blackwood.}
\FunctionTok{with\_family}\NormalTok{(\{}
  \FunctionTok{plot\_lagged\_scatter\_grid}\NormalTok{(blackwood\_project, }\StringTok{\textquotesingle{}Blackwood\textquotesingle{}}\NormalTok{, }\AttributeTok{predictor =} \StringTok{\textquotesingle{}xgf\textquotesingle{}}\NormalTok{, }\AttributeTok{leads =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{9}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-11-1} \end{center}

For predictive lead-lag structure, the usable lead-side CCF is weak for both predictors. Restricting attention to leads 1 through 9 games, the largest save-percentage lead correlation has magnitude only 0.1011 and occurs at lead 4, while the largest team-xGF\% lead correlation has magnitude only 0.0723 and occurs at lead 8. The 3 by 3 lead-by-lead scatterplot grids for each predictor are also fairly diffuse, with no strong or stable linear pattern across leads 1 through 9. Even though these relations are weak, in sports data, I can only really take what I'm given, so for part (e), I will carry forward lead 4 for save percentage and lead 8 for team xGF\%.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ACF of the response series for possible autoregressive carryover.}
\FunctionTok{with\_family}\NormalTok{(\{}
  \FunctionTok{plot\_response\_acf}\NormalTok{(blackwood\_project, }\StringTok{\textquotesingle{}Blackwood\textquotesingle{}}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-12-1} \end{center}

At the end, I also check the ACF of the response because that is the only series for which a lagged autoregressive term might be added to the regression model. For Blackwood, the full ACF through lag 9 does not show any especially strong spike, so there is no strong autoregressive signal. Still, if I take the largest visible response-side candidate, it is around lag 4 with \(\rho(4) \approx -0.1088\), so I carry \(G_{t-4}\) into part (e) as the most plausible extra response lag.

\subsubsection{Shesterkin}\label{shesterkin-1}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Lead{-}only CCF plots for Shesterkin.}
\FunctionTok{with\_family}\NormalTok{(\{}
  \FunctionTok{plot\_goalie\_ccf}\NormalTok{(shesterkin\_project, }\StringTok{\textquotesingle{}Shesterkin\textquotesingle{}}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-13-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Scatterplots of lagged save percentage against future GSAx for Shesterkin.}
\FunctionTok{with\_family}\NormalTok{(\{}
  \FunctionTok{plot\_lagged\_scatter\_grid}\NormalTok{(shesterkin\_project, }\StringTok{\textquotesingle{}Shesterkin\textquotesingle{}}\NormalTok{, }\AttributeTok{predictor =} \StringTok{\textquotesingle{}sv\textquotesingle{}}\NormalTok{, }\AttributeTok{leads =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{9}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-14-1} \end{center}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Scatterplots of lagged team xGF\% against future GSAx for Shesterkin.}
\FunctionTok{with\_family}\NormalTok{(\{}
  \FunctionTok{plot\_lagged\_scatter\_grid}\NormalTok{(shesterkin\_project, }\StringTok{\textquotesingle{}Shesterkin\textquotesingle{}}\NormalTok{, }\AttributeTok{predictor =} \StringTok{\textquotesingle{}xgf\textquotesingle{}}\NormalTok{, }\AttributeTok{leads =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{9}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-15-1} \end{center}

On the predictive lead side of the CCF, save percentage shows a modest relationship with future GSAx. Over leads 1 through 9 games, the largest save-percentage lead correlation is -0.1762 at lead 2, while team xGF\% remains weak, with largest absolute correlation only 0.076 at lead 4. The 3 by 3 save-percentage scatterplot grid shows that the negative pattern is most visible at the shorter leads, especially around the selected two-game lead, while the team-xGF\% grid remains diffuse throughout. Again, even though the lead relations are not large in magnitude, I will carry forward lead 2 for save percentage and lead 4 for team xGF\%.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ACF of the response series for possible autoregressive carryover.}
\FunctionTok{with\_family}\NormalTok{(\{}
  \FunctionTok{plot\_response\_acf}\NormalTok{(shesterkin\_project, }\StringTok{\textquotesingle{}Shesterkin\textquotesingle{}}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-16-1} \end{center}

At the end, I also check the ACF of the response because that is the only series for which a lagged autoregressive term might be added to the regression model. For Shesterkin, the full ACF is more informative than just lag 1: lag 1 is small \(\rho(1) \approx -0.0308\), but there is a noticeable negative spike at lag 2 with \(\rho(2) \approx -0.1684\). So \(G_{t-2}\) is at least a plausible additional candidate regressor for part (e).

\newpage

\subsection{Problem 3 (e)}\label{problem-3-e}

\begin{problem}[Problem 3 (e)]
Propose and fit a time series regression model for your detrended and deseasonalized response variable. Report the fitted model and discuss goodness of fit of this model.
\end{problem}

For the forecast-accuracy summaries reported below, I use the aligned train-test split at matched career game number \(t=216\). This is Blackwood's first Colorado game in the matched sample, so observations with \(t < 216\) form the training set and observations with \(t \ge 216\) form the test set for both goalies.

\subsubsection{Blackwood Model}\label{blackwood-model}

For Blackwood, I use the lag choices suggested by part (d), namely lead 4 for save percentage, lead 8 for team xGF\%, and the strongest response-side ACF candidate \(G_{t-4}\). The model is
\[
G_t = \beta_0 + \beta_1 S_{t-4} + \beta_2 X_{t-8} + \beta_3 G_{t-4} + W_t.
\]
The fitted equation is
\[
\widehat{G_t} = 0.839751 - 0.543763 S_{t-4} - 0.008309 X_{t-8} - 0.082838 G_{t-4}
\]
where \(G_t\) is Blackwood's game-by-game even-strength GSAx in goals, \(S_t\) is Blackwood's game-by-game even-strength save percentage as a proportion, and \(X_t\) is Blackwood's team game-by-game even-strength xGF\% in percentage points. Since the largest lag used here is 8, the aligned fitted sample has \(n=277\) games.

\begin{itemize}
\tightlist
\item
  \(\hat{\beta}_1=-0.5438\) means a 0.01 increase in \(S_{t-4}\) is associated with an average change of -0.0054 goals in current \(G_t\), holding \(X_{t-8}\) and \(G_{t-4}\) fixed.
\item
  \(\hat{\beta}_2=-0.0083\) means a one-percentage-point increase in \(X_{t-8}\) is associated with an average change of -0.0083 goals in current \(G_t\), holding the other regressors fixed.
\item
  \(\hat{\beta}_3=-0.0828\) means a one-goal increase in \(G_{t-4}\) is associated with an average change of -0.0828 goals in current \(G_t\), holding \(S_{t-4}\) and \(X_{t-8}\) fixed.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit the Blackwood lagged regression and inspect the summary.}
\NormalTok{blackwood\_lag\_model}\SpecialCharTok{$}\NormalTok{fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## stats::lm(formula = fit_form, data = dat)
## 
## Coefficients:
## (Intercept)           sv          xgf         gLag  
##    0.839751    -0.543763    -0.008309    -0.082838
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(blackwood\_lag\_model}\SpecialCharTok{$}\NormalTok{fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## stats::lm(formula = fit_form, data = dat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.1895 -1.0794  0.0652  0.9892  3.1494 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)
## (Intercept)  0.839751   1.664419   0.505    0.614
## sv          -0.543763   1.764601  -0.308    0.758
## xgf         -0.008309   0.006709  -1.238    0.217
## gLag        -0.082838   0.099809  -0.830    0.407
## 
## Residual standard error: 1.382 on 273 degrees of freedom
## Multiple R-squared:  0.01744,    Adjusted R-squared:  0.006648 
## F-statistic: 1.616 on 3 and 273 DF,  p-value: 0.186
\end{verbatim}

\begin{center}
\scriptsize
\begin{table}[H]

\caption{\label{tab:blackwood-lag-reg-coef}Blackwood Lagged Regression Coefficients}
\centering
\begin{tabular}[t]{ccccc}
\toprule
Term & Estimate & Std. Error & t Value & P-value\\
\midrule
Intercept & 0.839751 & 1.664419 & 0.504531 & 0.6143\\
$S_{t-4}$ & -0.543763 & 1.764601 & -0.308150 & 0.7582\\
$X_{t-8}$ & -0.008309 & 0.006709 & -1.238496 & 0.2166\\
$G_{t-4}$ & -0.082838 & 0.099809 & -0.829973 & 0.4073\\
\bottomrule
\end{tabular}
\end{table}
\normalsize
\end{center}

\begin{center}
\scriptsize
\begin{table}[H]

\caption{\label{tab:blackwood-lag-reg-fit}Blackwood Lagged Regression Fit Criteria}
\centering
\begin{tabular}[t]{cccccc}
\toprule
\# Parameters & $R_a^2$ & $p_F$ & AIC & AICc & BIC\\
\midrule
4 & 0.0066 & 0.1860 & 3.5064 & 1.6693 & 3.5718\\
\bottomrule
\end{tabular}
\end{table}
\normalsize
\end{center}

\begin{center}
\scriptsize
\begin{table}[H]

\caption{\label{tab:blackwood-lag-reg-fc}Blackwood Lagged Regression Forecast Accuracy}
\centering
\begin{tabular}[t]{ccccc}
\toprule
ME & MPE & MSE & MAE & MAPE\\
\midrule
0.5223 & 126.4016 & 1.7263 & 1.0844 & 189.8653\\
\bottomrule
\end{tabular}
\end{table}
\normalsize
\end{center}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Diagnostic plots for the Blackwood lagged regression.}
\FunctionTok{with\_family}\NormalTok{(\{}
  \FunctionTok{plot\_model\_diagnostics}\NormalTok{(blackwood\_lag\_model, }\StringTok{\textquotesingle{}Blackwood\textquotesingle{}}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-18-1} \end{center}

For Blackwood, the final model still fits weakly even after using the strongest available lagged terms from part (d). The adjusted \(R^2\) is only 0.0066, the overall F-test p-value is 0.1860, and the residual standard error is 1.3819 goals. None of the three lagged regressors is statistically significant at the 5\% level, and the diagnostic plots do not suggest a strong systematic relation. Overall, Blackwood's final lagged regression is not a particularly strong model, even after taking the most favorable lead and response-lag choices from part (d).

\subsubsection{Shesterkin Model}\label{shesterkin-model}

For Shesterkin, I again use the lag choices suggested by part (d), namely lead 2 for save percentage, lead 4 for team xGF\%, and the response-side ACF candidate \(G_{t-2}\). The model is
\[
G_t = \beta_0 + \beta_1 S_{t-2} + \beta_2 X_{t-4} + \beta_3 G_{t-2} + W_t.
\]
The fitted equation is
\[
\widehat{G_t} = 1.968206 - 2.333501 S_{t-2} + 0.008648 X_{t-4} - 0.054451 G_{t-2}
\]
where \(G_t\) is Shesterkin's game-by-game even-strength GSAx in goals, \(S_t\) is Shesterkin's game-by-game even-strength save percentage as a proportion, and \(X_t\) is Shesterkin's team game-by-game even-strength xGF\% in percentage points. Since the largest lag used here is 4, the aligned fitted sample has \(n=281\) games.

\begin{itemize}
\tightlist
\item
  \(\hat{\beta}_1=-2.3335\) means a 0.01 increase in \(S_{t-2}\) is associated with an average change of -0.0233 goals in current \(G_t\), holding \(X_{t-4}\) and \(G_{t-2}\) fixed.
\item
  \(\hat{\beta}_2=0.0086\) means a one-percentage-point increase in \(X_{t-4}\) is associated with an average change of 0.0086 goals in current \(G_t\), holding the other regressors fixed.
\item
  \(\hat{\beta}_3=-0.0545\) means a one-goal increase in \(G_{t-2}\) is associated with an average change of -0.0545 goals in current \(G_t\), holding \(S_{t-2}\) and \(X_{t-4}\) fixed.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit the Shesterkin lagged regression and inspect the summary.}
\NormalTok{shesterkin\_lag\_model}\SpecialCharTok{$}\NormalTok{fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## stats::lm(formula = fit_form, data = dat)
## 
## Coefficients:
## (Intercept)           sv          xgf         gLag  
##    1.968206    -2.333501     0.008648    -0.054451
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(shesterkin\_lag\_model}\SpecialCharTok{$}\NormalTok{fit)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## stats::lm(formula = fit_form, data = dat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.2455 -0.9468  0.1657  0.9079  2.7080 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)
## (Intercept)  1.968206   1.902056   1.035    0.302
## sv          -2.333501   2.098823  -1.112    0.267
## xgf          0.008648   0.007220   1.198    0.232
## gLag        -0.054451   0.115525  -0.471    0.638
## 
## Residual standard error: 1.336 on 277 degrees of freedom
## Multiple R-squared:  0.03727,    Adjusted R-squared:  0.02684 
## F-statistic: 3.575 on 3 and 277 DF,  p-value: 0.01449
\end{verbatim}

\begin{center}
\scriptsize
\begin{table}[H]

\caption{\label{tab:shesterkin-lag-reg-coef}Shesterkin Lagged Regression Coefficients}
\centering
\begin{tabular}[t]{ccccc}
\toprule
Term & Estimate & Std. Error & t Value & P-value\\
\midrule
Intercept & 1.968206 & 1.902056 & 1.034778 & 0.3017\\
$S_{t-2}$ & -2.333501 & 2.098823 & -1.111814 & 0.2672\\
$X_{t-4}$ & 0.008648 & 0.007220 & 1.197847 & 0.2320\\
$G_{t-2}$ & -0.054451 & 0.115525 & -0.471336 & 0.6378\\
\bottomrule
\end{tabular}
\end{table}
\normalsize
\end{center}

\begin{center}
\scriptsize
\begin{table}[H]

\caption{\label{tab:shesterkin-lag-reg-fit}Shesterkin Lagged Regression Fit Criteria}
\centering
\begin{tabular}[t]{cccccc}
\toprule
\# Parameters & $R_a^2$ & $p_F$ & AIC & AICc & BIC\\
\midrule
4 & 0.0268 & 0.0145 & 3.4388 & 1.6017 & 3.5036\\
\bottomrule
\end{tabular}
\end{table}
\normalsize
\end{center}

\begin{center}
\scriptsize
\begin{table}[H]

\caption{\label{tab:shesterkin-lag-reg-fc}Shesterkin Lagged Regression Forecast Accuracy}
\centering
\begin{tabular}[t]{ccccc}
\toprule
ME & MPE & MSE & MAE & MAPE\\
\midrule
-0.1073 & 81.9792 & 2.2879 & 1.1701 & 118.4206\\
\bottomrule
\end{tabular}
\end{table}
\normalsize
\end{center}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Diagnostic plots for the Shesterkin lagged regression.}
\FunctionTok{with\_family}\NormalTok{(\{}
  \FunctionTok{plot\_model\_diagnostics}\NormalTok{(shesterkin\_lag\_model, }\StringTok{\textquotesingle{}Shesterkin\textquotesingle{}}\NormalTok{)}
\NormalTok{\})}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=\linewidth]{Homework5_files/figure-latex/unnamed-chunk-20-1} \end{center}

For Shesterkin, the final lagged model performs better than Blackwood's, although it is still only modest in strength. The lagged save-percentage coefficient remains the main significant term, while the lagged team-xGF\% term and the added \(G_{t-2}\) term are not statistically significant in the full regression. The adjusted \(R^2\) is 0.0268, the overall F-test p-value is 0.0145, and the residual standard error is 1.3362 goals. Overall, this is a modest but defensible model for Shesterkin.

\end{document}
